# Generated by Django 3.0.2 on 2020-02-17 18:00

from django.db import migrations

def forwards_func(apps, schema_editor):
    # Load models for make changes
    contact_model = apps.get_model("mainapp", "Contact")
    product_cat_model = apps.get_model("mainapp", "ProductCategory")
    product_model = apps.get_model("mainapp", "Product")

    # Create contacts
    contact_model.objects.create(
        pk=1,
        state="Colifornia",
        city="Los Angeles",
        phone="1900-1234-5678",
        email="info.california@iterrior.com",
        address="9 W 2 st Street, 60001",
    )
    contact_model.objects.create(
        pk=2,
        state="Illinois",
        city="Chicago",
        phone="1900-6789-0123",
        email="info.illinois@iterior.com",
        address="603 Brazos Street, 78701",
    )
    contact_model.objects.create(
        pk=3,
        state="Texas",
        city="Austin",
        phone="1900-5678-1234",
        email="info.texas@iterior.com",
        address="450 East North Street, 60611",
    )
    
    # Create product category
    new_product_cat = product_cat_model.objects.create(
        pk=1,
        name = "home",
        description = "household products",
    )
    # Create product
    product_model.objects.create(
        pk=3,
        category = new_product_cat,
        name = "tableware",
        image = "products_images/product-3.jpg",
        short_desc = "home cookware",
        description = "unique home cookware",
        price = "36",
        quantity = 15,
    )
    product_model.objects.create(
        pk=6,
        category = new_product_cat,
        name = "home chair",
        image = "products_images/product-21.jpg",
        short_desc = "home chair trending",
        description = "home chair home",
        price = "324",
        quantity = 36,
    )
    product_model.objects.create(
        pk=9,
        category = new_product_cat,
        name = "classic tableware",
        image = "products_images/product-5.jpg",
        short_desc = "classic tableware trending",
        description = "classic tableware",
        price = "441",
        quantity = 63,
    )

    # Delete link for product category
    del new_product_cat

    # Create product category
    new_product_cat = product_cat_model.objects.create(
        pk=2,
        name= "office",
        description= "office supplies",
    )
    # Create product
    product_model.objects.create(
        pk=5,
        category = new_product_cat,
        name = "interior light",
        image = "products_images/product-11.jpg",
        short_desc = "interior light trending",
        description = "interior light interior light",
        price = "54",
        quantity = 27,
    )

    product_model.objects.create(
        pk=8,
        category = new_product_cat,
        name = "interior light",
        image = "products_images/product-41.jpg",
        short_desc = "interior light trending",
        description = "interior light interior light",
        price = "153",
        quantity = 18,
    )
    # Delete link for product category
    del new_product_cat

    # Create product category
    new_product_cat = product_cat_model.objects.create(
        pk=3,
        name= "furniture",
        description= "furniture shop",
    )
    # Create product

    product_model.objects.create(
        pk=7,
        category = new_product_cat,
        name = "lampa",
        image = "products_images/product-31.jpg",
        short_desc = "table lamp trending",
        description = "modern table lamp",
        price = "423",
        quantity = 5,
    )

    product_model.objects.create(
        pk=15,
        category = new_product_cat,
        name = "comfortable chair",
        image = "products_images/product-7.jpg",
        short_desc = "comfortable chair",
        description = "modern comfortable chair",
        price = "423",
        quantity = 6,
    )
    # Delete link for product category
    del new_product_cat

    # Create product category
    new_product_cat =product_cat_model.objects.create(
        pk=4,
        name= "modern",
        description= "modern furniture store",
    )
    # Create product

    product_model.objects.create(
        pk=1,
        category = new_product_cat,
        name = "lamp",
        image = "products_images/product-1.jpg",
        short_desc = "night lamp",
        description = "modern night light",
        price = "179",
        quantity = 15,
    )

    product_model.objects.create(
        pk=4,
        category = new_product_cat,
        name = "chair",
        image = "products_images/product-4.jpg",
        short_desc = "office chair",
        description = "modern office chair",
        price = "261",
        quantity = 36,
    )

    product_model.objects.create(
        pk=10,
        category = new_product_cat,
        name = "modern tableware",
        image = "products_images/product-6.jpg",
        short_desc = "modern tableware trending",
        description = "modern tableware",
        price = "153",
        quantity = 54,
    )

    # Delete link for product category
    del new_product_cat

    # Create product category
    new_product_cat =product_cat_model.objects.create(
        pk=5,
        name= "classic",
        description= "classic furniture store",
    )
    # Create product

    product_model.objects.create(
        pk=2,
        category = new_product_cat,
        name = "armchairs",
        image = "products_images/product-2.jpg",
        short_desc = "classic armchairs",
        description = "beautiful classic armchairs",
        price = "321",
        quantity = 8,
    )
    
    product_model.objects.create(
        pk=11,
        category = new_product_cat,
        name = "wall lamp",
        image = "products_images/product-2-sm.jpg",
        short_desc = "classic armchairs exclusive",
        description = "beautiful classic armchairs",
        price = "522",
        quantity = 10,
    )
    
    product_model.objects.create(
        pk=12,
        category = new_product_cat,
        name = "sofa",
        image = "products_images/product-3-sm.jpg",
        short_desc = "classic armchairs exclusive",
        description = "beautiful classic armchairs",
        price = "351",
        quantity = 18,
    )
    
    product_model.objects.create(
        pk=13,
        category = new_product_cat,
        name = "Wall Clock",
        image = "products_images/product-4-sm.jpg",
        short_desc = "classic armchairs exclusive",
        description = "beautiful classic armchairs",
        price = "151",
        quantity = 27,
    )

    product_model.objects.create(
        pk=14,
        category = new_product_cat,
        name = "exclusive lamp",
        image = "products_images/product-5-sm.jpg",
        short_desc = "classic armchairs exclusive",
        description = "beautiful classic armchairs",
        price = "243",
        quantity = 72,
    )

def reverse_func(apps, schema_editor):
    # Load model for make changes

    product_cat_model = apps.get_model("mainapp", "ProductCategory")
    product_model = apps.get_model("mainapp", "Product")  
    contact_model = apps.get_model("mainapp", "Contact") 
    
    # Delete all objects
    product_cat_model.objects.all().delete()
    product_model.objects.all().delete()
    contact_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)
    ]
