# Generated by Django 3.0.2 on 2020-02-13 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_contact_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
