# Generated by Django 3.0.2 on 2020-02-25 09:32

from django.db import migrations

def forwards_func(apps, schema_editor):
    product_option_model = apps.get_model("mainapp", "Product_option")
    # Create option product
    
    product_option_model.objects.create(
        pk=1,
        product_id =4,
        name = "chair",
        option = "red",
        image = "products_images/product-4.jpg",
    )  

    product_option_model.objects.create(
        pk=2,
        product_id =4,
        name = "chair",
        option = "blue",
        image = "products_images/product-4-blue.jpg",
    )   

    product_option_model.objects.create(
        pk=3,
        product_id=4,
        name = "chair",
        option = "green",
        image = "products_images/product-4-green.jpg",
    ) 
    product_option_model.objects.create(
        pk=4,
        product_id=15,
        name = "comfortable chair",
        option = "green",
        image = "products_images/product-7-green.jpg",
    )

    product_option_model.objects.create(
        pk=5,
        product_id=15,
        name = "comfortable chair",
        option = "red",
        image = "products_images/product-7.jpg",
    )  

    product_option_model.objects.create(
        pk=6,
        product_id=15,
        name = "comfortable chair",
        option = "blue",
        image = "products_images/product-7-blue.jpg",
    ) 

def reverse_func(apps, schema_editor):
    # Load model for make changes
    product_option_model = apps.get_model("mainapp", "Product_option") 
    # Delete all objects
    product_option_model.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_product_option'),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)
    ]
